### ISSUE TITLE
Use source maps

### ISSUE THREAD

**Issue by hurrymaplelad** [karma-runner/karma-chrome-launcher#1]
Can we launch Chrome with source maps enabled so stack traces reference orignal line numbers when test are browserified?

Seems like there should be a CLI flag but [I haven't found it yet](http://stackoverflow.com/questions/15606621/chrome-command-line-flag-for-source-maps).  Also seems like the setting is stored somewhere in the `user-data-dir`.  There might be a configuration file we can copy into the temp dir.

**Comment by Dignifiedquire** [comment]
Custom flags are now supported. So closing this.
