### ISSUE TITLE
Getting "no compatible version found: isexe@^2.0.0" 

### ISSUE THREAD

**Issue by londondev** [karma-runner/karma-chrome-launcher#113]
Hi,
I am getting "no compatible version found: isexe@^2.0.0" while I am trying to install karma-chrome-launcher.

Any solution?

Regards,
Londondev

**Comment by rogeriopvl** [comment]
@londondev more info please. Can you paste the error log here?

**Comment by londondev** [comment]
(node:15580) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma-chrome-launcher"
npm ERR! node v6.8.1
npm ERR! npm  v3.6.0

npm ERR! No compatible version found: isexe@^2.0.0
npm ERR! Valid install targets:
npm ERR! 1.1.2, 1.1.1, 1.1.0, 1.0.1, 1.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by londondev** [comment]
isexe 2.0.0 is not downloadable from npm at the moment and seems karma-chrome-launcher has dependency it. Is there any workaround to point dependency to previous version of isexe?

**Comment by rogeriopvl** [comment]
@londondev that's weird. I just did an `npm install isexe` and it worked 🤔

**Comment by londondev** [comment]
this might be due our local npm repository. Thanks
