### ISSUE TITLE
ChromeHeadless still openes a window on Windows

### ISSUE THREAD

**Issue by doberkofler** [karma-runner/karma-chrome-launcher#122]
When using the ChromeHeadless laucher on the Windows platform, an empty window still will be opened while running the tests.

**Comment by tsneed290** [comment]
Same thing happens to me, I'm on a Mac.

**Comment by doberkofler** [comment]
To make sure that this is a problem in chrome itself, I also opened a chrome issue
https://bugs.chromium.org/p/chromium/issues/detail?id=718134

**Comment by tsneed290** [comment]
@doberkofler I looked at your chromium ticket. It said you were using 58. Was that a typo? Headless is supported in 59+. I saw a window display using Chrome Canary v60.

**Comment by rogeriopvl** [comment]
This isn't related with karma-chrome-launcher.

It can be reproduced without karma: 
- Open terminal
- Run chrome with the headless flags: `--headless --disable-gpu --remote-debugging-port=9222 `

The same will happen. Except that on Chrome Canary v60 (mac) it does not open a window, but the terminal window loses focus.

For now, I'll leave this issue open for reference.

**Comment by tsneed290** [comment]
@rogeriopvl You're correct. I see a Chrome Canary (60) icon pop up in my Dock, but there is no window. Ignore my previous comments; I must've been using an older Chrome version at the time of my initial writing.

**Comment by rogeriopvl** [comment]
Closing this since this is an issue with chrome headless itself and not this launcher.
