### ISSUE TITLE
How to launch --headless on Docker or wercker?

### ISSUE THREAD

**Issue by Quramy** [karma-runner/karma-chrome-launcher#125]
Hi. I want to run `ChromeHeadless` on CI services.

I could not launch `google-chrome --headless` because the following error:

```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

Is there some workarounds?

- CI conf script: https://github.com/Quramy/angular-karma-chrome-headless-demo/blob/master/wercker.yml#L28
- result of running on wercker CI: https://app.wercker.com/Quramy/angular-karma-chrome-headless-demo/runs/build/590c7c4da73a560001067c6e?step=590c7c514a016c0001f00fbe

I tried to run in local env(macOS Chrome canary), and it works well.

**Comment by andybry** [comment]
Hi,

I was getting this issue as well. For me adding the `--privileged` flag when running `docker run` resolved the issue.

The complete command I ran when starting the Docker container was: `docker run -it --privileged -v $(pwd):${MOUNT_POINT} ${DOCKER_IMAGE} bash`

Hope that helps you too!

**Comment by Quramy** [comment]
I tried `--privileged` flag on my local Docker host and the error was removed.
I don't know how to customise this flag on Wercker CI, so I'll search for information a little more.

Thanks!

**Comment by hoeck** [comment]
There is no need to start a privileged container, turning off the chrome sandbox with `--no-sandbox` is enough. Added the following to my `karma.conf.js`:

        browsers: ['ChromeHeadlessNoSandbox'],
        customLaunchers: {
            ChromeHeadlessNoSandbox: {
                base: 'ChromeHeadless',
                flags: [
                    '--no-sandbox', // required to run without privileges in docker
                    '--user-data-dir=/tmp/chrome-test-profile',
                    '--disable-web-security'
                ]
            }
        },

**Comment by andybry** [comment]
Hi @hoeck 

I agree that's a better solution if it works. However, it didn't work for me at the time I wrote the above comment.

**Comment by sam0104** [comment]
Where this file is located karma.conf.js  ? I do not see any such file while made a find / -name "karma.conf.js"   inside the container as root user.

**Comment by fatihdestegul** [comment]
> There is no need to start a privileged container, turning off the chrome sandbox with `--no-sandbox` is enough. Added the following to my `karma.conf.js`:
> 
> ```
>     browsers: ['ChromeHeadlessNoSandbox'],
>     customLaunchers: {
>         ChromeHeadlessNoSandbox: {
>             base: 'ChromeHeadless',
>             flags: [
>                 '--no-sandbox', // required to run without privileges in docker
>                 '--user-data-dir=/tmp/chrome-test-profile',
>                 '--disable-web-security'
>             ]
>         }
>     },
> ```

For continuous integration, it will be better setting them with a variable. So that you can run tests on your local with real browsers while you are testing it with headless in CI.

_karma.conf.js_
```
 const isBuild = process.env.CI;
  let settings = {
  ....
  ....
  ....
}
if (isBuild) {
    settings = {
      ...settings,
      browsers: ['ChromeHeadlessNoSandbox'],
      customLaunchers: {
        ChromeHeadlessNoSandbox: {
          base: 'ChromeHeadless',
          flags: ['--no-sandbox']
        }
      },
    };
  }

config.set(settings);
```

**Comment by teacherpan** [comment]
> There is no need to start a privileged container, turning off the chrome sandbox with `--no-sandbox` is enough. Added the following to my `karma.conf.js`:
> 
> ```
>     browsers: ['ChromeHeadlessNoSandbox'],
>     customLaunchers: {
>         ChromeHeadlessNoSandbox: {
>             base: 'ChromeHeadless',
>             flags: [
>                 '--no-sandbox', // required to run without privileges in docker
>                 '--user-data-dir=/tmp/chrome-test-profile',
>                 '--disable-web-security'
>             ]
>         }
>     },
> ```

worked for me , thank u.
