### ISSUE TITLE
ChromiumHeadless

### ISSUE THREAD

**Issue by RomkeVdMeulen** [karma-runner/karma-chrome-launcher#127]
I'm trying to configure Karma to use `ChromeHeadless` by default and headless Chromium as a fallback. Right now I have to configure headless Chromium myself:

```js
customLaunchers: {
	"ChromiumHeadless": {
		base: "Chromium",
		flags: [
			"--headless",
			" --remote-debugging-port=9222",
			// https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
			"--disable-gpu",
		],
	},
}
```

Could the `ChromiumHeadless` browser be included with this launcher by default, like is already the case with `ChromeHeadless`?

**Comment by GFoley83** [comment]
@RomkeVdMeulen you need to replace `Chrome` with `ChromiumHeadless` the `browsers` sections of your `karma.conf.js`. See here:
http://cvuorinen.net/2017/05/running-angular-tests-in-headless-chrome/
