### ISSUE TITLE
How to ensure team-members have ChromeHeadless available?

### ISSUE THREAD

**Issue by mikefisher84** [karma-runner/karma-chrome-launcher#130]
I'm trying to migrate my team off of phantomjs to ChromeHeadless. However the 2 big questions that keep popping up are: 

1. How do we make sure everyone has ChromeHeadless available and the same version?

2. How do we make our unit tests run on a CI box that doesn't have any browsers installed at all?

I've looked around and am struggling to answer both of these questions. Any ideas?

**Comment by zowers** [comment]
alternative: use [Puppeteer](https://github.com/googlechrome/puppeteer) instead which embeds Chrome inside the package

**Comment by alexan** [comment]
the downloader code from puppeteer could be found in this two files:
https://github.com/GoogleChrome/puppeteer/blob/1f9b4fb4c83ad9f5963507675e6ad9011c4301ff/install.js
https://github.com/GoogleChrome/puppeteer/blob/1f9b4fb4c83ad9f5963507675e6ad9011c4301ff/utils/ChromiumDownloader.js
