### ISSUE TITLE
Set TLS certificates to chrome headless

### ISSUE THREAD

**Issue by ogis-onishi** [karma-runner/karma-chrome-launcher#140]
I am trying to test MQTT client using MQTT.js and Chrome headless. My client code running on Chrome use MQTT over websocket secure (TLS) so the Chrome must includes self signed CA certificate to connect the MQTT broker or web server.

In this case, how can I set my self signed certificate to Chrome headless?

**Comment by rogeriopvl** [comment]
This should be asked to the chrome team. I would recommend the [Chromium mailing list](https://groups.google.com/a/chromium.org/forum).
