### ISSUE TITLE
After Chrome 60 update, Chrome cannot be started with headless flag

### ISSUE THREAD

**Issue by rokaskuciauskas** [karma-runner/karma-chrome-launcher#142]
09 08 2017 15:34:05.351:ERROR [launcher]: Cannot start Chrome
        [0809/153405.307:ERROR:process_info.cc(632)] range at 0x7a23727c00000000, size 0x17 fully unreadable
[0809/153405.308:ERROR:process_info.cc(632)] range at 0x7a23729c00000000, size 0x17 fully unreadable
[0809/153405.308:ERROR:process_info.cc(632)] range at 0x7a23729e00000000, size 0x17 fully unreadable

**Comment by BurningDog** [comment]
I'm on a Mac and running Chrome 60. Headless mode is still working. I have the following in my karma.conf.js

```
    customLaunchers: {
      ChromeHeadless: {
        base: 'Chrome',
        flags: [
          '--disable-translate',
          '--headless',
          '--disable-gpu',
          '--disable-extensions',
          '--remote-debugging-port=9222',
        ],
      }
    }

```

**Comment by tomas-ortega** [comment]
I'm sorry, i wasn't set the CHROME_BIN environment variable
I was set to: CHROME_BIN=/usr/bin/chromium-browser

And Working Now! :+1:

**Comment by rogeriopvl** [comment]
@rokaskuciauskas I'm closing this. If this is still an issue, please reopen and provide more info.

**Comment by thirusabari** [comment]
Hi @tomas-ortega ,

Could you please tell me, how to set the "Chrome Bin Environment Variable?

And also in which file , I have to set the chrome Environment in karma config file or gulp file?
