### ISSUE TITLE
Set url to chrome instance under karma

### ISSUE THREAD

**Issue by JustBBox** [karma-runner/karma-chrome-launcher#148]
I want to unit test ui component methods/properties that are available through url. Is it possible to set up url to chrome instance that is up by karma. Maybe there some options in the custom launcher?

**Comment by icfantv** [comment]
If I understand what you're asking, we're actually looking into this as well, but this doesn't even appear [to be a feature](https://developers.google.com/web/updates/2017/04/headless-chrome) of Chrome Headless - at least I can't find it.  Until Chrome Headless supports it, karma can't do anything.

**Comment by rogeriopvl** [comment]
Closing this as it's related directly with Chrome Headless and not karma-chrome-launcher.
