### ISSUE TITLE
[heads-up] puppeteer.executablePath() is introduced

### ISSUE THREAD

**Issue by aslushnikov** [karma-runner/karma-chrome-launcher#153]
Hi,

I've seen you're reaching out to ChromiumDownloader to get the executable path in your [README.md](https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer):

```js
// karma.conf.js

const ChromiumRevision = require('puppeteer/package.json').puppeteer.chromium_revision
const Downloader = require('puppeteer/utils/ChromiumDownloader')
const revisionInfo = Downloader.revisionInfo(Downloader.currentPlatform(), ChromiumRevision)

process.env.CHROME_BIN = revisionInfo.executablePath

module.exports = function(config) {
  config.set({
    browsers: ['ChromeHeadless']
  })
}
```

A few minutes ago, Puppeteer got a [`puppeteer.executablePath()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerexecutablepath) method introduced, so there would be no need to reach to undocumented ChromiumDownloader in future.

Note: the method is a part of Puppeteer 0.11.0, which is not released yet.

**Comment by rogeriopvl** [comment]
Thanks for the heads-up @aslushnikov, I'll keep this open as a reminder until Puppetteer 0.11.0 is released.

**Comment by aslushnikov** [comment]
@rogeriopvl pptr v0.11.0 is live now: https://github.com/GoogleChrome/puppeteer/releases/tag/v0.11.0

**Comment by rogeriopvl** [comment]
@aslushnikov thanks. Code example updated in: [6f41067](https://github.com/karma-runner/karma-chrome-launcher/commit/6f410675d06b4aabcfc94f5f80a19e2eed5af4dc)

**Comment by donaldpipowitch** [comment]
I wonder if it's really necessary to call `process.env.CHROME_BIN = require('puppeteer').executablePath()`? I run a CI test on Travis without this line and everything seemed to work correctly. AFAIK there is no Chrome installed on Travis by default and I haven't enabled it manually either. I just added `puppeteer` as a dependency.

**Comment by rogeriopvl** [comment]
@donaldpipowitch Have you checked your `.travis.yml` file? You may have it configured to install chrome. AFAIK it shouldn't work without puppeteer 🤔

**Comment by donaldpipowitch** [comment]
This is our  `.travis.yml` https://github.com/Mercateo/ws/blob/master/.travis.yml.
