### ISSUE TITLE
Keeping Chrome --headless running in the background for faster test execution

### ISSUE THREAD

**Issue by w0rp** [karma-runner/karma-chrome-launcher#160]
I run karma tests for an AngularJS project myself. On my machine it takes around 40 seconds to start running tests with the `--headless` version of Chrome. The Chrome process is launched to run the tests, and killed after testing ends.

Would it be possible to have an option to keep headless chrome running in the background so I could start running my tests more quickly?

**Comment by canado** [comment]
I am looking for the same feature, like keeping chrome open 24/7

Did you find a way?

**Comment by vlodko** [comment]
Use `ChromeHeadless` browser

**Comment by w0rp** [comment]
That's what I've been using for months. I'd like to have the ability to keep the browser running in the background.

**Comment by vlodko** [comment]
@w0rp have you tried adding `--headless` flag?

**Comment by w0rp** [comment]
Yeah, it's headless. I want it to keep running after karma exits, and reconnect when I start tests again. I want the browser to stay open in the background until I kill it.

**Comment by johnjbarton** [comment]
>  I want the browser to stay open in the background until I kill it.

I think you want to run with `--no-single-run` and `--auto-watch`

I don't think 'in the background' is useful.

**Comment by w0rp** [comment]
I do think it is useful. I want to keep the browser running in the background, completely rebuild all of my scripts from scratch, and run the tests with that headless browser again. Currently it takes around 40 seconds for Chrome to start on my machine, so I have to wait an extra 40 seconds for the tests to start running.

**Comment by w0rp** [comment]
I'll note that PhatomJS didn't have these issues. It would start up almost instantly, and that meant my tests executed faster. Now that project is defunct, I'm left with Chrome. The results are more accurate, but the tests don't execute as quickly as they used to.

**Comment by johnjbarton** [comment]
I guess by "in the background" you meant "an a process that does not exit" rather than "a background process", ie
https://unix.stackexchange.com/questions/82934/what-is-a-background-process

Did you try the command line options?  Did the browser not stay open until you killed it?
