### ISSUE TITLE
--enable-logging flag might be a sensible default

### ISSUE THREAD

**Issue by vemv** [karma-runner/karma-chrome-launcher#162]
HI there!

I use the same Karma setup for OSX and Linux, but the linux one logs nothing.

Apparently Chrome has the `--enable-logging` flag, which is not at use in the project. Maybe it's redundant in most cases (particularly OSX), but in Linux I'm definitely not seeing any logging, so maybe  adding the flag would be a good default?

(assuming the flag works)

Unfortunately I'm not using karma directly (but via a complex wrapper) so I'd have it hard to try out this myself.

WDYT?

Cheers - Victor

**Comment by Mogztter** [comment]
@vemv Even with the custom flag `--enable-logging` nothing is showing in the console:


```js
module.exports = function (config) {
  config.set({
    frameworks: ['jasmine'],
    files: [
      'spec/**/*-spec.js'
    ],
    reporters: ['progress'],
    port: 9876, // karma web server port
    colors: true,
    logLevel: config.LOG_DEBUG,
    browsers: ['chrome_with_log'],
    customLaunchers: {
      chrome_with_log: {
        base: 'ChromeHeadless',
        flags: ['--enable-logging']
      }
    },
    autoWatch: false,
    concurrency: Infinity
  });
};
```

In my code I'm using `console.log`.
Am I missing something ?

**Comment by rogeriopvl** [comment]
Logging should be something set explicitly by the user. And you can do that by creating a custom launcher.
