### ISSUE TITLE
Ignore .ts by ChromeHeadless

### ISSUE THREAD

**Issue by ringtail003** [karma-runner/karma-chrome-launcher#176]
Hi.

I would like execute testing with Karma(ChromeHeadless) & Webpack & TypeScript.
But seems like ChromeHeadless browsers ignored `preprocessors` setting.

My environment:

- macOS High Sierra
- node 9.9

## When using `PhantomJS`, Expected results are displayed.

<img width="882" alt="2018-04-07 12 14 44" src="https://user-images.githubusercontent.com/15980747/38450766-80634108-3a5e-11e8-9baa-7a79da836326.png">

## When using `ChromeHeadless`, Nothing was loaded.

<img width="940" alt="2018-04-07 12 14 01" src="https://user-images.githubusercontent.com/15980747/38450778-b8d15aa2-3a5e-11e8-9f3b-bec8e328b40e.png">

Are there something wrong?

<details>
  <summary>/package.json</summary>
  <pre>
{
  "name": "karma-webpack-typescript",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "webpack": "webpack",
    "test": "karma start --auto-watch --no-single-run"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babylon": "^7.0.0-beta.42",
    "rimraf": "^2.6.2",
    "ts-loader": "^4.1.0",
    "typescript": "^2.8.1",
    "webpack": "^4.3.0",
    "webpack-cli": "^2.0.13",
    "webpack-merge": "^4.1.2"
  },
  "devDependencies": {
    "@types/jasmine": "^2.8.6",
    "jasmine-core": "^3.1.0",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-mocha-reporter": "^2.2.5",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^3.0.0",
    "puppeteer": "^1.2.0"
  }
}
  </pre>
</details>

<details>
  <summary>/karma.conf.json</summary>
  <pre>
process.env.CHROME_BIN = require('puppeteer').executablePath();

module.exports = function(config) {
  var webpackConfig = require('./webpack/test.config.js');

  config.set({
    basePath: './src/',
    frameworks: ['jasmine'],
    files: [
        { pattern: '**/*.ts', watched: false },
    ],
    exclude: [],
    preprocessors: {
      '**/*.js': ['sourcemap'],
      '**/*.ts': ['webpack', 'sourcemap'],
    },
    webpack: webpackConfig,
    reporters: ['mocha'],
    mochaReporter: {
      output: 'minimal',
      divider: '='
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    //browsers: ['PhantomJS'],
    browsers: ['ChromeHeadless'],
    singleRun: true,
    concurrency: Infinity
  })
}
  </pre>
</details>

<details>
  <summary>/tsconfig.json</summary>
  <pre>
{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": true,
    "module": "es6",
    "target": "es5",
    "sourceMap": true,
    "allowJs": true,
    "lib": ["es5", "es2015", "dom"]
  }
}
  </pre>
</details>

<details>
  <summary>/webpack.config.js</summary>
  <pre>
const path = require('path');

module.exports = {
  entry: './src/index.ts',
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      }
    ]
  },
  resolve: {
    extensions: [ '.ts', '.js' ],
    modules: [
      path.resolve(__dirname, 'src'),
      path.resolve(__dirname, 'node_modules'),
    ],
  },
};
  </pre>
</details>

<details>
  <summary>/webpack/test.config.js</summary>
  <pre>
const path = require('path');
const merge = require('webpack-merge');
const webpack = require('webpack');
const baseConfig = require('../webpack.config');

const config = {
  mode: 'development',
  devtool: 'inline-source-map',
  resolve: {
    extensions: ['.ts', '.js'],
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        exclude: path.resolve(__dirname, '../node_modules/'),
        test: /\.js$/,
        loader: 'source-map-loader',
      },
    ],
  },
  plugins: [
    new webpack.SourceMapDevToolPlugin({
      filename: null,
      test: /\.(ts|js)($|\?)/i
    })
  ]
};

module.exports = merge(baseConfig, config);
  </pre>
</details>

<details>
  <summary>/src/index.ts</summary>
  <pre>
// nothing
  </pre>
</details>

<details>
  <summary>/src/specs.js</summary>
  <pre>
Error.stackTraceLimit = Infinity;
var testContext = require.context('./', true, /\.spec\.ts$/);

function requireAll(requireContext) {
    return requireContext.keys().map(requireContext);
}
var modules = requireAll(testContext);

  </pre>
</details>

<details>
  <summary>/src/test.spec.ts</summary>
  <pre>
it('test', () => {
  expect(1).toBe(100);
});
  </pre>
</details>

Cheers.

**Comment by redi-wadash** [comment]
From https://github.com/angular/angular-cli/issues/2838#issuecomment-265782400, adding `mime: { "text/x-typescript": ["ts", "tsx"] }` to the `karma.conf.js` helped me.

I don't know much about how Karma launchers work, but it would be nice if it worked out of the box for TypeScript too.

**Comment by ringtail003** [comment]
@redi-wadash 

Great! Your solution as works well.
Thanks for helping me.

Solved. 👍
