### ISSUE TITLE
"Executed i of n" output on multiple lines?

### ISSUE THREAD

**Issue by glvangorp** [karma-runner/karma-chrome-launcher#178]
I was curious how to adjust this output:

![screen shot 2018-04-30 at 11 24 32 am](https://user-images.githubusercontent.com/13023351/39435338-23367960-4c69-11e8-8429-8fd95dea362f.png)

Theoretically I would like to have the line updated with the current progress i.e. "Executed 2 of 258" on a single line. I'm not sure why they are breaking up into three separate lines. Can anyone shed some light on why this is happening or how to configure it to only output a single line?

**Comment by stephendougherty** [comment]
Getting this issue myself after recently upgrading my Karma configuration and experimenting with Chrome headless. It was fine before I upgraded. Changed too many things though to know what it is for sure.

**Comment by joshua-mbg** [comment]
@rogeriopvl 
_ping_

**Comment by rogeriopvl** [comment]
I'm going to close this since it should be reported in the [karma-runner/karma](https://github.com/karma-runner/karma) repo. karma-chrome-launcher is not responsible for that output, it just launches chrome browsers.
