### ISSUE TITLE
How to inspect tests with devtools?

### ISSUE THREAD

**Issue by trusktr** [karma-runner/karma-chrome-launcher#179]
Now that I have failing tests, how to I use devtools to inspect the tests with breakpoints?

Is there a way to make Chrome headless pause so that I can press play in devtools to let it run (similar to `--inspect-brk` for Node apps)?

I have 

```js
        browsers: ['MyChromeHeadless'],
        customLaunchers: {
            MyChromeHeadless: {
                base: 'ChromeHeadless',
                flags: [ '--remote-debugging-port=9222' ],
            },
        },
```

in my karma config, and I can manage to load that page, but the tests end quickly before I have time to do anything. Is there was a way to make it start in paused mode, and then step over the lines with devtools?

**Comment by trusktr** [comment]
I'm in Ubuntu inside Chrome OS, launching tests in Chrome headless. I think I can try to run the tests in non-headless for debugging.

With Node apps, I don't need to launch the Linux desktop, I can just visit `chrome://inspect` in Chrome OS Chrome, and see the app there, and it will be paused (--inspect-brk) and ready for me to debug.

Can this be done with Chrome headless?

**Comment by johnjbarton** [comment]
karma-runner is a node app: use node debugging to debug the runner.
karma tests are in-browser. Use chrome devtools to debug.  

I seriously doubt chrome devtools can work in headless, but you can ask them.

**Comment by trusktr** [comment]
We'll, you'd think chrome//:inspect from a Chrome window would be smart enough to detect a Chrome-headless window like it does with Node apps, but that doesn't seem to be the case yet (or at least it isn't simple like with Node). Then it would be easy to open devtools on it.

I will see if it is possible...

**Comment by tchakabam** [comment]
maybe i am missing something here, but wondering why did you need to run dev-tools in a headless browser here? just run the full-on beast? :)

**Comment by tchakabam** [comment]
if you want to enforce breakpoint on load similar to node's `--inspect-brk`,  i'd hack that with a `debugger;` statement at the top of whichever module you'd have as entry point to your import chain :)
