### ISSUE TITLE
afterEach runs before test completes

### ISSUE THREAD

**Issue by rohitsainimonotype** [karma-runner/karma-chrome-launcher#184]
describe.only('temp', () => {
    beforeEach(() => {
        console.log('beforeEach');
    })
    afterEach(() => {
        console.log('afterEach');
    })
    it('temp test', (done) => {
        setTimeout(() => {
            console.log('setTimeout');
            done();
        }, 1000);
    })
})

When I am running this in karma-chrome 'setTimeout'  prints after 'afterEach'. What I expect afterEach should be called after test completes . But I'm running it with mocha it is working fine.

**Comment by Alber70g** [comment]
Any further info on this. I'm experiencing this issue as well.

**Comment by johnjbarton** [comment]
This is an issue with jasmine, karma-runner can't fix it.
