### ISSUE TITLE
how to set the default language for the chrome

### ISSUE THREAD

**Issue by shaoping** [karma-runner/karma-chrome-launcher#19]
in index.js 
![image](https://cloud.githubusercontent.com/assets/6847589/3687454/c69ef96c-1327-11e4-9821-e3e409d0dab2.png)

this set the default config for the chrome ,how should I set the language

**Comment by phacks** [comment]
I know this issue has been closed for a long time, however I have a use case for the ability to change the language : I run a French Chrome, our website is localized and we run our tests on Circle CI (localized in English). On tests that matches strings that depend on the language, tests that are passing on Circle CI fail on my local environment.
