### ISSUE TITLE
Setting specFilter directly on Env is deprecated

### ISSUE THREAD

**Issue by dotnetCarpenter** [karma-runner/karma-chrome-launcher#190]
When I run tests now, I get the following:

HeadlessChrome 0.0.0 (Ubuntu 0.0.0) ERROR: 'DEPRECATION:', 'Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`'

For now it's ok. But one day it will probably fail.

**Comment by dotnetCarpenter** [comment]
```json
"jasmine-core": "^3.3.0",
"karma": "^3.1.1",
"karma-chrome-launcher": "^2.2.0",
"karma-coverage": "^1.1.2",
"karma-firefox-launcher": "^1.1.0",
"karma-jasmine": "^1.1.2",
```

**Comment by abdelkrimdev** [comment]
Hello!!!
You have to update the `karma-jasmine` to the latest version `2.0.0` this will fix the issue.
Thanks 😄

**Comment by dotnetCarpenter** [comment]
@abdelkrimdev Thanks, that works!

**Comment by mowali** [comment]
My karma-jasmine is set to latest 2.0.1 but still getting error. I just updated to Angular 7 and TypeScript 3.2
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage": "^1.1.2",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-trx-reporter": "^0.4.0",

**Comment by proAppleEater** [comment]
I'm in the exact same situation as mowali !

**Comment by ovitrif** [comment]
Same

**Comment by rogeriopvl** [comment]
@mowali @proAppleEater @ovitrif This issue is not related with `karma-chrome-launcher`. Please check: https://github.com/karma-runner/karma-jasmine/issues/221

**Comment by shardulsonar** [comment]
How to check the version of karma-jasmine ?

**Comment by johnjbarton** [comment]
Look in `node_modules/karma-jasmine/package.json`

**Comment by lenichols** [comment]
Updating Karma-Jasmine to 2.0.1 solved this for me. Thnks!

**Comment by Yagnadat-Talakola** [comment]
Thanks for raising the issue @dotnetCarpenter, I've had a similar issue today. Upgrading the version to 2.0.0 helped remove it.

**Comment by johnjbarton** [comment]
You probably want 2.0.1... but 3.0.1 is out.
