### ISSUE TITLE
Karma can't stay connected to Chrome 73

### ISSUE THREAD

**Issue by andyearnshaw** [karma-runner/karma-chrome-launcher#196]
My machine updated Chrome to 73 today.  Following that, I am getting the following error after my tests have run the first time, whilst waiting for file changes:

```
25 03 2019 11:21:23.525:WARN [HeadlessChrome 73.0.3683 (Mac OS X 10.13.6)]: Disconnected (0 times)reconnect failed before timeout of 10000ms (transport close)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR
  Disconnectedreconnect failed before timeout of 10000ms (transport close)
```

If I make further changes to the file, I get the following warning:

```
25 03 2019 11:24:29.076:WARN [karma]: No captured browser, open http://localhost:9876/
```

If I open http://localhost:9876/ I see the Karma logo flash up, the tests run again, then this message:

```
25 03 2019 11:24:56.196:WARN [Chrome 73.0.3683 (Mac OS X 10.13.6)]: Disconnected (0 times)Client disconnected from CONNECTED state (transport error)
Chrome 73.0.3683 (Mac OS X 10.13.6) ERROR
  DisconnectedClient disconnected from CONNECTED state (transport error)
```

Followed by "Aw, snap!" in the browser window.  Things I've tried for a fix:

 1. Terminal restart
 2. Killing all chrome instances before starting
 3. Restarting the machine
 4. Reinstalling all node modules
 5. Updating karma and karma-chrome-launcher

Nothing has worked.

**Comment by andyearnshaw** [comment]
Update: it looks like the browser is crashing, but only if tests are skipped. This is pretty weird.  Also, it appears to only affect tests that make use of the new constructable stylesheets feature, so I'm going to close this as it is most definitely a browser bug.

**Comment by maartendebal** [comment]
Hi @andyearnshaw  is there a bug report in Chrome for this? I can't seem to find it. 
I'm having the same issue on TFS CI server.

**Comment by andyearnshaw** [comment]
@maartendebal there is a bug report in Chrome, but I submitted it through my crash reports so you probably can't see it:

https://bugs.chromium.org/p/chromium/issues/detail?id=945363

You might need to submit your own crash reports to effectively "+1" the issue.

**Comment by maartendebal** [comment]
Thanks.

I've got it fixed by upgrading the Puppeteer and this downloaded a newer version of Chromium.

This thread did send me in the right direction.

**Comment by daytonpa** [comment]
https://github.com/karma-runner/karma-chrome-launcher/issues/154#issuecomment-495339829

**Comment by lachieh** [comment]
> Thanks.
> 
> I've got it fixed by upgrading the Puppeteer and this downloaded a newer version of Chromium.
> 
> This thread did send me in the right direction.

Just had a similar connection timeout issue. Updated `puppeteer` version also worked for me.
