### ISSUE TITLE
Override permissions API?

### ISSUE THREAD

**Issue by jportella93** [karma-runner/karma-chrome-launcher#199]
Hi, thanks for the great package!

I'm trying to access the `clipboard-read` API to read text copied to clipboard, but it requires a status granted on the [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions) and I can't figure out how to show the permission prompt and accept it.

I tried starting Chrome Headless with permissions API disabled, but then it just removes the access to the API so I cannot grant access to the clipboard:

```javascript
  browsers: [
      'CustomChromeHeadless',
    ],
    customLaunchers: {
      'CustomChromeHeadless': {
        base: 'ChromeHeadless',
        flags: [
          '--disable-permissions-api'
          ]
      }
    },
```

Is there any way I can do something similar to `overridePermissions` [as you can do in Puppeteer](https://developer.mozilla.org/en-US/docs/Web/API/Permissions)?:
```javascript
const context = browser.defaultBrowserContext();
await context.overridePermissions('http://example.com', ['clipboard-read']);
```

**Comment by rogeriopvl** [comment]
Hi @jportella93 

AFAIK, there's no flag for that on Chrome (`karma-chrome-laucher` mainly builds the chrome command with all the configured/necessary flags).

A way to configure this in Chrome is to use the DevTools protocol and [`Browser.grantPermissions`](https://chromedevtools.github.io/devtools-protocol/tot/Browser#method-grantPermissions). So maybe you can somehow include that in your setup.

**Comment by Burtan** [comment]
Did you succeed?
