### ISSUE TITLE
publish new release to npm?

### ISSUE THREAD

**Issue by elpddev** [karma-runner/karma-chrome-launcher#200]
Hi,

Latest release in npm is 2.2.0 from 2017.
https://www.npmjs.com/package/karma-chrome-launcher

I see the master contains newer commits from 2019. 
It would be appreciated if this can be publish to npm.

**Comment by rogeriopvl** [comment]
@johnjbarton @dignifiedquire

**Comment by johnjbarton** [comment]
Done. Please check the release.
