### ISSUE TITLE
Google Chrome Headless stopped working on Chrome 76.X

### ISSUE THREAD

**Issue by KfirMarouani** [karma-runner/karma-chrome-launcher#211]
After chrome update to version 76 all test started failing on message:

```
HeadlessChrome 76.0.3809 (Mac OS X 10.14.6)
    ReferenceError: expect is not defined

```

Karma configuration is:

```
browsers: [
      'ChromeHeadless'
    ]
```

**Comment by johnjbarton** [comment]
This is not enough information to take action, but it is very unlikely that your issue can be fixed within karma-chrome-launcher. The error comes from within your test after chrome has launched.

The likely cause is a missing jasmine file in your test page, a file which would define `expect`.

**Comment by chadbr** [comment]
@KfirMarouani did you figure this out? I'm having similar issue... it's an Angular CLI project if that helps...

No error - chrome simply never launches (regular chrome or headless -- same behavior).

Thanks, Chad

**Comment by KfirMarouani** [comment]
Hi,
This is what solved it for me at the end:

…

browsers: [
  'MyChromeHeadless'
],
customLaunchers: {
MyChromeHeadless: {
    base: 'ChromeHeadless',
    flags: ['-disable-web-security'],
  },
}


..

Hope this helps!

**Comment by chadbr** [comment]
Thanks @KfirMarouani -- in my case, I just needed to remove node_modules and reinstall... I'm assuming there was some conflict between the local node_modules and the globally installed chrome.

Thanks for posting the info!

 Chad
