### ISSUE TITLE
Headless Chromium without Puppeteer

### ISSUE THREAD

**Issue by kmisha** [karma-runner/karma-chrome-launcher#237]
As I understand, we don't need Puppeteer to run headless Chromium.

Should we update docs? Because,  it still suggests installing puppeteer package.

**Comment by jginsburgn** [comment]
I think so! Can you submit a PR?

**Comment by kmisha** [comment]
Of course.

**Comment by pariaSadatHosseiny** [comment]
Hello every one,
is there any doc for using karma-chrome-luncher without puppeteer?
we are having some issues on using puppeteer on jenkins on a EKS cluster and it can not start the chromium, so wanted to know how to use it without puppeteer ?
