### ISSUE TITLE
Cannot start Dartium Error: spawn EACCES

### ISSUE THREAD

**Issue by ufoscout** [karma-runner/karma-chrome-launcher#32]
Hi all,

It's being many days that I try to solve this issue without luck.
The karma config file is:

```
module.exports = function(config) {
  config.set({
    basePath: '.',
    frameworks: ['dart-unittest'],

    files: [
      {pattern: 'test/angular_ui_tests.dart',  included: true},
      {pattern: '**/*.dart', included: false},
      {pattern: '**/*.html', included: false}
    ],

    exclude: [
    ],

    autoWatch: true,
    captureTimeout: 60000,
    browserNoActivityTimeout: 300000,
    

    plugins: [
      'karma-dart',
      'karma-chrome-launcher'
    ],

    browsers: ['Dartium']
  });
};
```

The global variable DARTIUM_BIN is defined. The dartium executable file has permission 777. The file path reported in DARTIUM_BIN is correct. 
I can launch dartium manually from command line or from the Dart Editor with no issues.
The error message is too generic and does not help so much:
```
INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser Dartium
ERROR [launcher]: Cannot start Dartium
        Error: spawn EACCES
INFO [launcher]: Trying to start Dartium again (1/2).
ERROR [launcher]: Cannot start Dartium
        Error: spawn EACCES
INFO [launcher]: Trying to start Dartium again (2/2).
ERROR [launcher]: Cannot start Dartium
        Error: spawn EACCES
ERROR [launcher]: Dartium failed 2 times (cannot start). Giving up.
```
The operating system is kubuntu 14.04.
nodejs is v0.10.33 and everything works fine except for this issue.
The same issue happens with a direct nodejs installation or through nvm.

Regards
Francesco

**Comment by Dignifiedquire** [comment]
Hey thanks for the report, could you do me a favor and check if this is still an issue with the latest versions of karma and karma-chrome-launcher.

**Comment by ufoscout** [comment]
@Dignifiedquire
When I reported this issue I was collaborating with the angular-dart-ui team; however, now I am not involved in that project any more. So, I am sorry, but I do not have a direct way of testing it  :disappointed:

**Comment by Dignifiedquire** [comment]
Thanks, closing this for now, if it's still an issue someone else will file a new bug :)
