### ISSUE TITLE
Headless chromium for linux

### ISSUE THREAD

**Issue by kmalakoff** [karma-runner/karma-chrome-launcher#39]
Hi there,

We have been hitting our heads against a wall trying to get browser tests running on Jenkins with mocha and PhantomJS for our browser uploader. Basically, there is a known bug with PhantomJS where attaching a blob doesn't transfer the full file and fails to have correct content-length.

We were thinking about trying to run Chromium on linux in a headless mode to avoid the problems with PhantomJS.

We've seen your issue [here](https://github.com/karma-runner/karma-chrome-launcher/issues/10) and solutions [here](https://www.npmjs.com/package/run-headless-chromium) and [here](https://gist.github.com/addyosmani/5336747). 

Would you be willing to upgrade this module to have a 'headless' option that runs chrome/chromium using xvfb?

**Comment by Krinkle** [comment]
See also #20. This can be done already by starting an Xvfb window before you call karma (or npm-test, or grunt), and exposing the relevant `DISPLAY` environment variable.

To support this from within Karma, it would most likely have to be done within the core Karma framework. The launcher plugins just abstract discovery of the binary and configuration of relevant command line arguments. Not creation of the temp directory or launching of the process itself.

See karma-runner/karma#1320 for supporting Xvfb.

**Comment by Dignifiedquire** [comment]
Closing this in favor of the tracking issue https://github.com/karma-runner/karma/issues/1320 as this needs to be done in core. As @Krinkle mentioned the current workaround is to use xfvb similar to how we use it for travis tests using firefox here: https://github.com/karma-runner/karma/blob/master/.travis.yml#L21-L22
