### ISSUE TITLE
No README data

### ISSUE THREAD

**Issue by kentcdodds** [karma-runner/karma-chrome-launcher#40]
When I npm install this package I get the error:

```
npm WARN package.json karma-chrome-launcher@0.1.4 No README data
```

Normally I only see that when a package doesn't have a README.md file, but this one has one, so I'm not sure what the problem is. You'll notice that it doesn't have any README.md data on the package listing on [npmjs.org](https://www.npmjs.com/package/karma-chrome-launcher). But I'd really like to get rid of this warning as it clutters up my warnings and makes it difficult for me to find real issues.

**Comment by AaronBuxbaum** [comment]
I'm having the same issue, along with `karma-phantomjs-launcher` and `karma-firefox-launcher`. It seems that the `README.md` file just has to be added to the npm repo.

**Comment by nottinhill** [comment]
+1

**Comment by Krinkle** [comment]
The karma-chrome-launcher@0.1.7 package from npm contains:
```
├── LICENSE
├── index.js
├── package.json
└── test
    └── jsflags.spec.js
````

Tree at v0.1.7 in Git contains:
```
├── CONTRIBUTING.md
├── Gruntfile.coffee
├── LICENSE
├── README.md
├── index.js
├── package.json
└── test
    └── jsflags.spec.js
```

Maybe it's caught by `.npmignore` somehow. I don't see how though.

**Comment by zzo** [comment]
fixed

**Comment by Krinkle** [comment]
@zzo Cool! I'm curious how you fixed it?

**Comment by zzo** [comment]
Ha am not sure why this was a problem before - the repo had a README.md so
all should have been good.
I see now the package.json in the npm registry has the README embedded in
it (and 'readmeFillename' set properly) so am wondering if a later version
of npm does this.  https://github.com/npm/npm/issues/3573  although that
thread is old I wonder if there has been other newer changes that are not
that obvious.
  Mark
