### ISSUE TITLE
No README data

### ISSUE THREAD

**Issue by nottinhill** [karma-runner/karma-chrome-launcher#43]
npm WARN package.json karma-chrome-launcher@0.1.7 No README data

**Comment by Krinkle** [comment]
Duplicate of #40.

**Comment by zzo** [comment]
fixed

**Comment by nottinhill** [comment]
Cool, 1 down, 15 to go (dependencies in my project who forgot the README)

Am 16.04.2015 um 19:33 schrieb Mark Trostler:
