### ISSUE TITLE
Slow test execution if no part of Chrome window is visible

### ISSUE THREAD

**Issue by segrey** [karma-runner/karma-chrome-launcher#44]
Mac OS X 10.10.3
Google Chrome 42.0.2311.135 (64-bit)

**package.json**
```json
{
  "name": "slow-karma-tests",
  "version": "0.0.1",
  "devDependencies": {
    "karma": "0.12.32",
    "karma-chrome-launcher": "0.1.8",
    "karma-jasmine": "0.3.5"
  }
}
```

**karma.conf.js**
```javascript
module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine'],
        files: ['tests/spec.js'],
        reporters: ['progress'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_ERROR,
        autoWatch: true,
        browsers: ['Chrome'],
        singleRun: false
    });
};
```
**tests/spec.js**
```javascript
describe('Hello', function() {
  for (var i = 1; i <= 1000; i++) {
    it('World #' + i, function() {
      expect(true).toBeTruthy();
    })
  }
});
```

If a part of Chrome window is visible, tests are running as expected:
```
$ ./node_modules/karma/bin/karma run
Chrome 42.0.2311 (Mac OS X 10.10.3): Executed 1000 of 1000 SUCCESS (2.06 sec / 0.864 secs)
```

However, if Terminal window is maximized (by double clicking Terminal's title bar), so Chrome window is completely hidden, tests are run unexpectedly slowly:
```
$ ./node_modules/karma/bin/karma run
Chrome 42.0.2311 (Mac OS X 10.10.3): Executed 1000 of 1000 SUCCESS (50.592 sec / 49.125 secs)
```

Checking "Prevent App Nap" option for "Google Chrome" doesn't change anything.

It'd be great if Chrome window visibility wouldn't affect test execution time.

**Comment by segrey** [comment]
Looks like Chrome thinks that the captured Chrome page is inactive and enables inactive tab handling:
https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout#Inactive_tabs
>In (Firefox 5.0 / Thunderbird 5.0 / SeaMonkey 2.2) and Chrome 11, timeouts are clamped to firing no more often than once per second (1000 ms) in inactive tabs; see bug 633421 for more information about this in Mozilla or crbug.com/66078 for details about this in Chrome.

If it's indeed caused by inactive tab handling, then probably there a cli flag that disables inactive tab handling?

**Comment by samuelhorwitz** [comment]
:+1: This seems to have gotten really bad after upgrading to Chrome 42 and I cannot find any advanced flags or switches to turn off this inactive tab optimization.

**Comment by Dignifiedquire** [comment]
I don't think there is anything we can really do from our side I'm afraid. I will close this reluctantly, but feel very free to reopen/post another issue if you have any idea what we could do from our end to improve things around this.

**Comment by segrey** [comment]
Fair enough. Related issue https://code.google.com/p/chromium/issues/detail?id=485425

**Comment by kimardenmiller** [comment]
Same issue +1

**Comment by jamestalmage** [comment]
@segrey @kimardenmiller @samuelhorwitz 

I've ([created a workaround](https://github.com/karma-runner/karma/issues/1568)). Be aware that it does hack `setTimeout` in the browser, and certainly is not battle tested. Please give it a try and let me know if you run into issues:

```bash
 npm install --save-dev jamestalmage/karma#hack-timer
```

@Dignifiedquire 
I know it's a hackie fix, but until there is movement on the Chromium bug, I think it is kinda necessary. I have resorted to plugging in a second screen just to circumvent the issue. I'm sure my PR needs wider testing, but I would mark this a "high priority" as it severely hurts usability.

**Comment by jamestalmage** [comment]
correction, install via:
```
 npm install --save-dev jamestalmage/karma#hack-timer
```

**Comment by monkpit** [comment]
4 tests takes 31 seconds to execute with the window in the background, and .02 seconds with the window in the foreground. How can this be addressed? Is there a workaround other than making sure the window is "visible"?
