### ISSUE TITLE
Chromium support for Darwin and Windows

### ISSUE THREAD

**Issue by gmoz22** [karma-runner/karma-chrome-launcher#45]
Version 0.1.8 supports Chromium on linux but not on Darwin and Windows.

**Comment by gmoz22** [comment]
Version 0.1.8 supports Chromium on linux but not on Darwin and Windows.

**Comment by j0hnsmith** [comment]
+1

**Comment by sechel** [comment]
+1

**Comment by Ciantic** [comment]
It's quiet simple to hack it to work by editing karma-chrome-launcher in node_modules:
https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L48

But I think there could be a option "chromePath" where one could define absolute path to chromium. In windows it's usually not installed, but unzipped in random location, so having such elaborate guessing algorithm is not working.

**Comment by Ciantic** [comment]
Found a workaround, which is a good one:

Just throw this in top of your "karma.conf.js":

`process.env['CHROME_BIN'] = "C:\\Copies\\Chromium\\chrome.exe";`

No need to monkey patch.
