### ISSUE TITLE
Can't open browsers installed in user's Application directory on OSX

### ISSUE THREAD

**Issue by natecavanaugh** [karma-runner/karma-chrome-launcher#54]
[Reposted](https://github.com/karma-runner/karma/issues/1375#issuecomment-102525141) by request of @Dignifiedquire 
I see in the launcher files for [Chrome](https://github.com/karma-runner/karma-chrome-launcher/blob/7f32b59d61232f3f377cc982975eef748bccdc11/index.js#L41-L76) and Firefox there are some lookups for both Windows and Linux to get the correct browser. However, with OSX, it's always being hardcoded to /Applications.
While I know this can be worked around by setting the CHROME_BIN and FIREFOX_BIN to the users Application directory, I think it's a common enough scenario that I imagine the launchers should at least attempt to see if it exists in ~/Applications first.

(As a side note, the files seem a little inconsistent in how they're looking up the different browsers, Opera doesn't appear to try to look up for any of the systems).

Is this something you guys would think about fixing?

**Comment by Dignifiedquire** [comment]
Thanks @natecavanaugh I think we should improve the look up to include `~/Applications`

**Comment by Dignifiedquire** [comment]
It looks like it's actually doing it in the latest version, first looking in the home directory: https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L90

**Comment by natecavanaugh** [comment]
Awesome, thank you! I think we can close this one then. Should I file a separate issue on the Firefox repo?

**Comment by Dignifiedquire** [comment]
Yes please, check if the behaviour is the same or if it differs before though :) thanks
