### ISSUE TITLE
Is it possible to not open a new Chrome instance?

### ISSUE THREAD

**Issue by cesarvarela** [karma-runner/karma-chrome-launcher#61]
Does not seem to be an option.

**Comment by FezVrasta** [comment]
+1

**Comment by razagill** [comment]
Anyone have an idea about this? I would like to keep my current browser session while testing.

**Comment by aaaaahaaaaa** [comment]
What is very painful IMO is that all the DevTool config is reset with this new instance (breakpoints, blackboxing, etc...)

**Comment by rogeriopvl** [comment]
Testing should be done with a clean session to avoid tainting your results. Unless there's a really good and plausible motive, I don't see why this should option be added.

Regarding the devtool configuration and quoting the README:
> The --user-data-dir is set to a temporary directory but can be overridden on a custom launcher as shown below. One reason to do this is to have a permanent Chrome user data directory inside the project directory to be able to install plugins there (e.g. JetBrains IDE Support plugin).

With this you can create a custom launcher based on Chrome that has a specific --user-data-dir, and you'll be able to control the chrome profile.
