### ISSUE TITLE
[launcher]: No binary for Chrome browser on your platform.

### ISSUE THREAD

**Issue by spagu** [karma-runner/karma-chrome-launcher#62]
FreeBSD is asking for ''Please, set "CHROME_BIN" env variable.'' What to do ?

**Comment by maksimr** [comment]
You should set global environment variable CHROME_BIN like PATH. You can put 'export CHROME_BIN=google-chrome' to .profile or if you use chromium to shold write something like CHROME_BIN=chromium-browser

**Comment by spagu** [comment]
Ok Thanks, I am just not sure about :do I need to have browser installed? 
I am trying to do tests against remote dedicated machine. Firefox works fine.

**Comment by maksimr** [comment]
@spagu browser should be installed on machine where you run tests

**Comment by maksimr** [comment]
Documentation about CHROME_BIN variable - http://karma-runner.github.io/0.13/config/browsers.html
section `Correct path to browser binary`
Feel free reopen

Thanks

**Comment by ddeveloperr** [comment]
The same problem on cloud9 IDE....details are [here](https://stackoverflow.com/questions/46033617/how-to-set-chrome-bin-env-variable-on-cloud9-ide-when-running-react-js-app)

Somebody deal with Cloud9 IDE please?

**Comment by mtizziani** [comment]
i use ubuntu with php-storm and chromium for my development an have done the following:

Terminal:

`export CHROME_BIN=/usr/bin/chromium-browser`

PHP-Storm:

1. install the plugin Karma
2. open project
3. Run -> Edit Configuration -> press + for add a new Karma Runner =>
  - set a name
  - select the karma.conf.json from your project dir
  - use "Chromium" as browser
4. run will open karma in a new Chromium Tab and all tests are running

**Comment by prashantidealittechno** [comment]
How can I add into node:lts-alpine3.11?

```yml
# base image
FROM node:lts-alpine3.11


# install chrome for protractor tests
RUN apk add chromium && \
    export CHROME_BIN='/usr/bin/chromium'

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# add app
COPY . /app

# start app
CMD ng serve --host 0.0.0.0
```

**Comment by KurisuLim** [comment]
Hello, @prashantidealittechno  I know it's over 5 years now since you left this comment. But I was wondering if you had solved this issue? I am new to docker and I am having the same problem.

**Comment by Appius** [comment]
@prashantidealittechno, @KurisuLim 

The issue is explained here - https://stackoverflow.com/a/33379487.
Basically, export is not working as you expect inside docker container. You need to use `ENV` instead.
```
FROM node:14-alpine
RUN apk add chromium
ENV CHROME_BIN='/usr/bin/chromium-browser'

...
RUN npm run test
```
Works fine for me.
