### ISSUE TITLE
Launch Chrome with --disable-background-timer-throttling flag

### ISSUE THREAD

**Issue by IgorMinar** [karma-runner/karma-chrome-launcher#64]
Chrome Canary will soon support `--disable-background-timer-throttling` flag. Karma should use it out of the box.

https://code.google.com/p/chromium/issues/detail?id=485425#c21

**Comment by pkozlowski-opensource** [comment]
Yay!

**Comment by zzo** [comment]
published to npm as v0.2.2

**Comment by jamestalmage** [comment]
Awesome!

**Comment by maxkostow** [comment]
What about setting [`--disable-renderer-backgrounding`](http://peter.sh/experiments/chromium-command-line-switches/#disable-renderer-backgrounding) as well? People on the linked issue are claiming `--disable-background-timer-throttling` isn't enough.

**Comment by zzo** [comment]
Hm ya maybe - never heard of that one - worth a shot - I'll try to repro
the failure

**Comment by zzo** [comment]
So I am having problems repro'ing this not working.  On Mac OSX Version 49.0.2623.87 (64-bit) just the  disable-background-timer-throttling flag works as intended.  When the Chrome window is minimized or hidden the tests still run at full speed, not throttled.  karma-chrome-launcher 0.2.2.
I will also comment on the chrome issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=485425&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by zzo** [comment]
ok I can repo this using the angular 1.x repo - bummer :(

**Comment by mgol** [comment]
@zzo Do you know why did the Chrome issue get restricted? I can no longer see it.

**Comment by zzo** [comment]
Hm yes looks like it has been restricted to Google.  The flag appears to
not work completely correctly on OSX but works on linux it about where
we're at so far.
I think they are going to fix the OSX issue but don't know when.

**Comment by mgol** [comment]
Thanks for the info. Why was it restricted? It'd be valuable to have a public-facing bug about this issue.

**Comment by zzo** [comment]
I don't know.  I asked if they were going to make another bug for the mac
issue.

**Comment by mgol** [comment]
Thx. Please let us know here when you have the answer.

**Comment by mgol** [comment]
Any updates? Do you know why is the bug hidden?

**Comment by zzo** [comment]
There have been no updates to the bug and I don't not know why it is now
hidden - I can ask

**Comment by mgol** [comment]
OK, please ask. :)

**Comment by mgol** [comment]
Any updates, @zzo?

**Comment by zzo** [comment]
Nope - no updates

**Comment by mgol** [comment]
But did you ask someone about the issue? Or not yet?

-- 
Michał Gołębiowski

**Comment by zzo** [comment]
I have asked but no response - i will reach out directly and see if I can
get a response.
  Mark

**Comment by zzo** [comment]
Ok a new bug was just forked off from the old bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=605498#c1
