### ISSUE TITLE
What is karma-chrome-launcher?

### ISSUE THREAD

**Issue by deleugpn** [karma-runner/karma-chrome-launcher#75]
As per the words, I think this will invoke an installed Chrome application from my environment, correct?
If that is the case, one can conclude that it's required to have Chrome installed on the operating system before being able to use this package. Am I correct so far?

My end problem is that my work environment is a CentOS without GUI (only CLI). How do people install Chrome on such environments? The closest I've got was `yum install google-chrome-stable` (after enabling google-chrome repository) and getting a **Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)**. I've lost a fair amount of time dealing with it and I would just like a confirmation that indeed these things are prerequisite to start using Karma with Chrome.

**Comment by brutalcrozt** [comment]
did you have `karma` and `karma-cli` ?

**Comment by MazeChaZer** [comment]
@Deleugpn Perhaps you can run Chrome in [Xvfb](https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml). Also on Linux, Chromium might be easier to install than Chrome.

**Comment by rogeriopvl** [comment]
As suggested you can run a headless chrome with xvfb, or even checkout the real headless chrome. So please check [this link](https://gist.github.com/addyosmani/5336747) for more info.
