### ISSUE TITLE
"No binary for Chrome browser on your platform"

### ISSUE THREAD

**Issue by borysn** [karma-runner/karma-chrome-launcher#77]
Hey guys!

I just made the upgrade to 2.0.0, and now I receive an error when running...

```console
ERROR [launcher]: No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.
```

The solution is pretty clear, I just run an `$ export CHROME_BIN=chromium` and it runs fine.

My question is, why did I not have to export a var in the previous release? Is there a way around this without setting a specific executable? I just foresee having ci issues down the road, or possibly cross platform issues with people pulling the project, but maybe I'm not looking at this correctly.

**Comment by borysn** [comment]
With a little further investigation, I think I may have answered my own question. It looks like with the 2.0.0 update the `Chrome` browser property no longer targets `Chromium` as well. I think it should though, so I guess I'm wondering why the change was made.

Updating my config like so also resolves the issue

__karma.conf.js__
```
...
browsers: [
      'Chromium'
    ],

    customLaunchers: {
      Chrome_travis_ci: {
        base: 'Chromium',
        chromeDataDir: path.resolve(__dirname, '.chrome'),
        flags: ['--no-sandbox']
      }
    },
...
```

**Comment by dignifiedquire** [comment]
That's why it was a major release. This makes sure that Chromium is supported on all operating systems and splits it out as it is a different browser like Dartium and as such a different binary. This makes it also easier to test both if you want to

**Comment by borysn** [comment]
@dignifiedquire gotcha, thanks for getting back to me on that.
