### ISSUE TITLE
Allow options to include installed apps, instead hard-coded setting

### ISSUE THREAD

**Issue by dougrchamberlain** [karma-runner/karma-chrome-launcher#78]
Chrome uses aggressive caching, and changes to spec files are not captured when karma is in autowatch mode.  I want to be able to disable caching, I already have a plugin that does that. but this hardcoded option keeps it from loading. 

![screenshot-of-chrome-network-log-showing-caching-occurring](https://cloud.githubusercontent.com/assets/4382701/19198310/77f2cb46-8c8c-11e6-968d-de4a220b2573.png)

**Comment by rogeriopvl** [comment]
@dougrchamberlain instead of enabling default apps, wouldn't it be a better solution to just add the "disable all cache" flags, and get the same result?

**Comment by rogeriopvl** [comment]
Closing this due lack of feedback.
