### ISSUE TITLE
ChromeDataDir doesn't work

### ISSUE THREAD

**Issue by quyetvivn** [karma-runner/karma-chrome-launcher#89]
I have config as below:
```
    browsers: ['Chromium', 'ChromiumWithData'],

    customLaunchers: {
      ChromiumWithData: {
        base: 'Chromium',
        chromeDataDir: __dirname + '/.chromium'
      }
    }
```
But when I run karma start --browsers ChromiumWithData, Karma doesn't use .chromium as dataDir. This is message from karma:
`31 12 2016 23:13:18.494:DEBUG [launcher]: /usr/bin/chromium --user-data-dir=/tmp/karma-38163120 --no-default-bro
wser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-backgrou
nd-timer-throttling http://localhost:9876/?id=38163120`

**Comment by maksimr** [comment]
@quyetvivn  only `Chrome`[*] support custom user-data-dir

[*] - Chrome https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L24
     - Chromium https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L85

Pull Request welcome

Thanks
